### ISSUE TITLE
Qiitaの手順通りに進めるとClass 'Predis\Client' not foundが発生する。

### ISSUE THREAD

**Issue by NobunagaProducts** [ucan-lab/docker-laravel5#18]
現時点でQiitaの記事のまま進めますと、[初めてブラウザに反映されるか確かめる時](https://qiita.com/ucan-lab/items/17c806973e69792ada99#laravelプロジェクトを新規に作成する場合)
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Predis\Client' not found`が発生します。
redis関係のエラーのようで
`docker-compose exec app composer require predis/predis`を実行すれば解決されるようです。
対応をお願いします。

**Comment by ucan-lab** [comment]
@NobunagaProducts お返事遅くなりました！
Qiitaの記事とREADMEの手順を更新しました。ご連絡ありがとうございます☺️
